[package]
name = "webserver-wasi-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
wasmtime = "0.39.1"
wasmtime-wasi = "0.39.1"
tiny_http = "0.11.0"
